name: Publish plugin

on:
  release:
    types: [published]

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: flutter-actions/setup-flutter@v3
        with:
          flutter-version: '3.19.6'
      - uses: flutter-actions/setup-pubdev-credentials@v1
      - name: Install dependencies
        run: flutter pub get
      - name: Publish
        run: flutter pub publish --force
